const manifest = require("./topogram-generator.json");

function slugify(value) { return String(value || "page").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "page"; }
function routeFileName(routePath) { return !routePath || routePath === "/" ? "index.html" : slugify(routePath) + ".html"; }
function routesFromContract(contract) {
  const screensById = new Map((contract.screens || []).map((screen) => [screen.id, screen]));
  const items = contract.navigation && contract.navigation.items || [];
  const routes = items.length > 0 ? items.map((item) => { const screen = screensById.get(item.screenId) || {}; return { screenId: item.screenId, path: item.route || screen.route || "/", title: screen.title || item.label || item.screenId || "Page" }; }) : (contract.screens || []).map((screen) => ({ screenId: screen.id, path: screen.route || "/", title: screen.title || screen.id || "Page" }));
  return routes.map((route) => ({ ...route, file: routeFileName(route.path) }));
}
function renderPackageJson(projectionId) { return `${JSON.stringify({ name: projectionId, private: true, version: "0.1.0", type: "module", scripts: { dev: "node ./scripts/dev.mjs", build: "node ./scripts/build.mjs", check: "node ./scripts/check.mjs" }, dependencies: { "@sveltejs/kit": "^2.9.0", "@sveltejs/vite-plugin-svelte": "^4.0.0", vite: "^5.4.11", svelte: "^5.0.0", typescript: "^5.6.3" } }, null, 2)}\n`; }
function renderHtml(title, brand, nav, projectionId, index, count) { return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>${title}</title><link rel="stylesheet" href="./styles.css" /></head><body><header><a href="./index.html">${brand}</a><nav>${nav.map((item) => `<a href="./${item.file}">${item.title}</a>`).join("")}</nav></header><main><section><p>Page ${index + 1} of ${count}</p><h1>${title}</h1><p>Generated by @attebury/topogram-generator-sveltekit-web from <code>${projectionId}</code>.</p></section></main><script src="./app.js" type="module"></script></body></html>\n`; }
function generate(context) {
  const contract = context.contracts && context.contracts.uiWeb;
  if (!contract) throw new Error("@attebury/topogram-generator-sveltekit-web requires contracts.uiWeb.");
  const routes = routesFromContract(contract);
  const projectionId = contract.projection && contract.projection.id || context.projection && context.projection.id || "proj_ui_web";
  const brand = contract.appShell && contract.appShell.brand || "Topogram SvelteKit";
  const nav = routes.map(({ title, file }) => ({ title, file }));
  const files = {
    "package.json": renderPackageJson(projectionId),
    "styles.css": "body{margin:0;font-family:Inter,system-ui,sans-serif;background:#f7f8fb;color:#17202a}header{display:flex;justify-content:space-between;gap:1rem;padding:1rem;border-bottom:1px solid #d9e0ea;background:#fff}nav{display:flex;gap:.75rem;flex-wrap:wrap}a{color:#0f5cc0}main{max-width:56rem;margin:0 auto;padding:2rem 1rem}section{background:#fff;border:1px solid #d9e0ea;border-radius:8px;padding:1.25rem}\n",
    "app.js": "document.documentElement.dataset.topogramGenerated = 'true';\n",
    "scripts/build.mjs": "import fs from 'node:fs';import path from 'node:path';const root=path.resolve(new URL('..', import.meta.url).pathname);const dist=path.join(root,'dist');fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});for (const entry of fs.readdirSync(root,{withFileTypes:true})) if(entry.isFile()&&['.html','.css','.js'].includes(path.extname(entry.name))) fs.copyFileSync(path.join(root,entry.name),path.join(dist,entry.name));console.log('Built web app to dist/.');\n",
    "scripts/check.mjs": "import fs from 'node:fs';const html=fs.readdirSync(new URL('..', import.meta.url)).filter((entry)=>entry.endsWith('.html'));if(html.length<1) throw new Error('Expected at least one HTML page.');console.log('Checked ' + html.length + ' generated web page(s).');\n",
    "scripts/dev.mjs": "import http from 'node:http';import fs from 'node:fs';import path from 'node:path';const root=path.resolve(new URL('..', import.meta.url).pathname);const port=Number(process.env.PORT||process.env.WEB_PORT||5173);http.createServer((req,res)=>{const url=new URL(req.url||'/', 'http://localhost:' + port);const file=url.pathname==='/'?'index.html':url.pathname.slice(1);const p=path.join(root,file);if(!fs.existsSync(p)){res.writeHead(404).end('Not found');return;}res.end(fs.readFileSync(p));}).listen(port,()=>console.log('Web app listening on http://localhost:' + port));\n"
  };
  routes.forEach((route, index) => { files[route.file] = renderHtml(route.title, brand, nav, projectionId, index, routes.length); });
  return { files, artifacts: { generator: manifest.id, projection: projectionId, routeCount: routes.length }, diagnostics: [] };
}
module.exports = { manifest, generate };
